In [2]:
 pip install numpy

Requirement already satisfied: numpy in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (2.2.6)Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np

In [4]:
# Create a numpy Array from Tuple
arr = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)

In [5]:
# Create an array of all zeros
arr = np.zeros((4,4))   
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [6]:
# Create an array of all ones
arr = np.ones((3,4))    
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [7]:
# Create an array filling all elements with a specified value
arr = np.full((4,3), 9)  
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]

In [8]:
# Create a 4x4 identity matrix
arr = np.eye(4)         
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [9]:
# Create an array filled with random values
arr = np.random.random((3,3))  
print(arr)

[[0.56287261 0.0859475  0.66878995]
 [0.29623386 0.73634874 0.38613007]
 [0.68058809 0.17825403 0.34010429]]

In [10]:
# Create an array with sequential values starting from 0 to a given range limit
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
# Create an array with sequential values starting from a given value to a final value and with a step value
arr = np.arange(0, 30, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
# Reshape the array to a new specified dimension
arr = np.arange(30)
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [13]:
# Reshape the array to a new specified dimension -- a shorter way
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
# Creating a string array 
arr = np.array([['John', 'Robert'], ['Pranav', 'Tauseef']])
arr

array([['John', 'Robert'],
       ['Pranav', 'Tauseef']], dtype='<U7')

In [15]:
# Create an array of dimension 5,6 using the arange function. 
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [16]:
# Return the dot product of two arrays
arr1 = np.arange(30).reshape(5,6)
print(arr1)
arr2 = arr1.T
print(arr2)
arr_res = arr1.dot(arr2)
print(arr_res)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
[[  55  145  235  325  415]
 [ 145  451  757 1063 1369]
 [ 235  757 1279 1801 2323]
 [ 325 1063 1801 2539 3277]
 [ 415 1369 2323 3277 4231]]

In [17]:
# Flatten an Array
arr1 = np.arange(30).reshape(5,6)
print(arr1)
arr = arr1.flatten()
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

In [18]:
# Find the Min, Max, Mean, Standard Deviation and Variance of the elements
arr1 = np.arange(30).reshape(5,6)
minm = arr1.min()
maxm = arr1.max()
mean = arr1.mean()
std = arr1.std(axis=1)  # Along Columns
var = arr1.var(axis=0)  # Along Rows
print("Minimum: ", minm)
print("Maximum: ", maxm)
print("Mean: ", mean)
print("Standard Deviation: ", std)
print("Variance: ", var)

Minimum:  0
Maximum:  29
Mean:  14.5
Standard Deviation:  [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
Variance:  [72. 72. 72. 72. 72. 72.]

In [19]:
# Create a copy
arr1 = np.arange(30).reshape(5,6)
arrc = arr1.copy()
print(arrc)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

In [20]:
# Rounding elements
arr1 = np.random.random((3,3)) 
print("Array 1: \n", arr1)
arr2 = arr1.round(2)
print("Array 2: \n", arr2)

Array 1:
 [[0.40950966 0.51023284 0.74959872]
 [0.441894   0.27585451 0.11911125]
 [0.62523726 0.84752195 0.65426515]]
Array 2:
 [[0.41 0.51 0.75]
 [0.44 0.28 0.12]
 [0.63 0.85 0.65]]

In [21]:
# Converting Data Types with astype
arr1 = np.arange(30).reshape(5,6)  
print("Array 1: \n", arr1)  
arr2 = arr1.astype(str)    # Convert elements from Int to String
print("Array 2: \n", arr2)
arr3 = arr2.astype(int)    # Convert String elements to Int again
print("Array 3: \n", arr3)

Array 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Array 2:
 [['0' '1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10' '11']
 ['12' '13' '14' '15' '16' '17']
 ['18' '19' '20' '21' '22' '23']
 ['24' '25' '26' '27' '28' '29']]
Array 3:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

In [22]:
# Accessing Array Elements - 2nd row, 3rd column
arr1 = np.arange(30).reshape(5,6)  
print("Array 1: \n", arr1)  
print("Element at the 2nd row, 3rd column: ", arr1[1, 2])

Array 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Element at the 2nd row, 3rd column:  8

In [23]:
# Accessing Array Elements 
arr1 = np.arange(30).reshape(5,6)  
print("Array 1: \n", arr1)  
print("Element at the 2nd row, 3rd column: ", arr1[1,2])   
print("All Elements on the 2nd row: ", arr1[1])   # Print the 2nd row
print("Element on the 3rd  column: ", arr1[:, 2])   # Print the 3rd column
print("All Elements: \n", arr1[:,:])   # Another way of doing this is not mentioning the indexes

Array 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Element at the 2nd row, 3rd column:  8
All Elements on the 2nd row:  [ 6  7  8  9 10 11]
Element on the 3rd  column:  [ 2  8 14 20 26]
All Elements:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

In [24]:
# Accessing Array Elements 
arr1 = np.arange(30).reshape(5,6)  
print("Array 1: \n", arr1)  
print("Elements on the 2nd row, 3rd to 5th positions: ", arr1[1, 2:5])   
print("Elements on the 3rd column, 3rd to 5th row positions: ", arr1[2:5, 2])   
# Elements on the 2nd row, 3rd to 5th positions, Elements on the 3rd column, 3rd to 5th row positions
print("Elements on the 2nd row, 3rd to 5th positions , Elements on the 3rd column, 3rd to 5th row positions :")
print(arr1[2:5, 2:5])

Array 1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Elements on the 2nd row, 3rd to 5th positions:  [ 8  9 10]
Elements on the 3rd column, 3rd to 5th row positions:  [14 20 26]
Elements on the 2nd row, 3rd to 5th positions , Elements on the 3rd column, 3rd to 5th row positions :
[[14 15 16]
 [20 21 22]
 [26 27 28]]

In [25]:
# Accessing Array Elements in a 3D array
arr1 = np.arange(64).reshape(4,4,4)  
print("Array 1: \n", arr1) 
print("Elements at the positions: first dimension: 0, second dimension: 3, third dimension: 2 :")
print(arr1[0, 3, 2])   
print("Elements at the positions: first dimension: 0, second dimension: positions 1st to 2nd, third dimension: 2 :")
print(arr1[0, 0:2, 2])

Array 1:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
Elements at the positions: first dimension: 0, second dimension: 3, third dimension: 2 :
14
Elements at the positions: first dimension: 0, second dimension: positions 1st to 2nd, third dimension: 2 :
[2 6]

In [26]:
# Iterating through Rows
arr1 = np.arange(30).reshape(5,6)  
print("Printing Through Rows:")
for row in arr1:      # Returns one row at a time - default
    print(row)
# Iterating through Rows
print("Printing Through Columns:")
cols = arr1.shape[1]   # Returns number of columns
for n in range(cols):
    print(arr1[:,n])  # Prints all elements on n-th column

Printing Through Rows:
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
Printing Through Columns:
[ 0  6 12 18 24]
[ 1  7 13 19 25]
[ 2  8 14 20 26]
[ 3  9 15 21 27]
[ 4 10 16 22 28]
[ 5 11 17 23 29]

In [27]:
# Horizontal Stacking of Two Arrays
arr1 = np.arange(30).reshape(5,6)
print("Array 1 :\n", arr1)
arr2 = np.arange(100, 130).reshape(5,6)
print("Array 2 :\n", arr2)
print("Stacked Array :\n", np.hstack((arr1, arr2)))

Array 1 :
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Array 2 :
 [[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]
Stacked Array :
 [[  0   1   2   3   4   5 100 101 102 103 104 105]
 [  6   7   8   9  10  11 106 107 108 109 110 111]
 [ 12  13  14  15  16  17 112 113 114 115 116 117]
 [ 18  19  20  21  22  23 118 119 120 121 122 123]
 [ 24  25  26  27  28  29 124 125 126 127 128 129]]

In [28]:
# Vertical Stacking of Two Arrays
arr1 = np.arange(30).reshape(5,6)
print("Array 1 :\n", arr1)
arr2 = np.arange(100, 130).reshape(5,6)
print("Array 2 :\n", arr2)
print("Stacked Array :\n", np.vstack((arr1, arr2)))

Array 1 :
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Array 2 :
 [[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]
Stacked Array :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]
 [100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]

In [29]:
# Vertical Splitting of Two Arrays
arr1 = np.arange(36).reshape(6,6)
print(arr1, '\n')
splt = np.vsplit(arr1, 2)
print(splt[0], '\n')
print(splt[1])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

In [30]:
# Horizontal Splitting of Two Arrays
arr1 = np.arange(36).reshape(6,6)
print(arr1, '\n')
splt = np.hsplit(arr1, 2)
print(splt[0], '\n')
print(splt[1])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]
 [24 25 26]
 [30 31 32]]

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]

In [31]:
# Demonstrate Array assignment
arr1 = np.arange(36).reshape(6,6)
arr2 = arr1       # arr2 is a reference to arr1, and not a physically different copy
arr1[1,1] = 99    # Change reflected in both arr1 and arr2
print("Array 1: \n", arr1)
print("Array 2: \n", arr2)

Array 1:
 [[ 0  1  2  3  4  5]
 [ 6 99  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Array 2:
 [[ 0  1  2  3  4  5]
 [ 6 99  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

In [32]:
# Demostrate Array Copy
arr1 = np.arange(36).reshape(6,6)
arr2 = arr1.copy()  # A physically different copy of the input array is created 
arr1[1,1] = 99      # Change reflected in both arr1 and arr2
print("Array 1: \n", arr1)
print("Array 2: \n", arr2)

Array 1:
 [[ 0  1  2  3  4  5]
 [ 6 99  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Array 2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

In [33]:
pip install pandas

Requirement already satisfied: pandas in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\91890\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
# Create my first Series Object
ser1 = pd.Series([3, 4, 8, 9, 5])
print(ser1)
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   # Specify the Index values
print(ser1)

0    3
1    4
2    8
3    9
4    5
dtype: int64
a    3
b    4
c    8
d    9
e    5
dtype: int64

In [5]:
# Create a Series Object using a Numpy Array

import numpy as np
arr = np.array([1,2,3,4,5])
ser1 = pd.Series(arr)
print(ser1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# Create a Series Object using a Dictionary
dict1 = {'a':1, 'b':2, 'c':3, 'd':4}
ser1 = pd.Series(dict1)
print("Import the whole Dictionary: \n", ser1)
ser1 = pd.Series(dict1, index=['c', 'b'])   # Explicitely mention which keys to import
print("Import Only specified Indexes from teh dictionary: \n", ser1)

Import the whole Dictionary:
 a    1
b    2
c    3
d    4
dtype: int64
Import Only specified Indexes from teh dictionary:
 c    3
b    2
dtype: int64

In [7]:
# Access elements of a Series object
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
print("Print the whole Series:\n", ser1)
print("Print the 3rd Element:\n", ser1[2])   # Access a single element
print("Print the elements between the 2nd to 4th positions:\n", ser1[1:4])   # Access a slice

Print the whole Series:
 a    3
b    4
c    8
d    9
e    5
dtype: int64
Print the 3rd Element:
 8
Print the elements between the 2nd to 4th positions:
 b    4
c    8
d    9
dtype: int64

C:\Users\91890\AppData\Local\Temp\ipykernel_21944\617439503.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Print the 3rd Element:\n", ser1[2])   # Access a single element

In [8]:
# Access elements of a Series object by specifying Index values
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
print("Print a slice using explicite indexes: \n", ser1['b':'d'])

Print a slice using explicite indexes:
 b    4
c    8
d    9
dtype: int64

In [9]:
# Access elements of a Series object by using the 'loc' 
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
print("Print a single element using explicit indexes with 'loc': \n", ser1.loc['b'])
print("Print a slice of elements using explicit indexes with 'loc': \n", ser1.loc['b':'d'])

Print a single element using explicit indexes with 'loc':
 4
Print a slice of elements using explicit indexes with 'loc':
 b    4
c    8
d    9
dtype: int64

In [10]:
# Access elements of a Series object by using the 'iloc' 
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
print("Print a single element using implicit indexes with 'iloc': \n", ser1.iloc[2])
print("Print a slice of elements using implicit indexes with 'iloc': \n", ser1.iloc[1:4])

Print a single element using implicit indexes with 'iloc':
 8
Print a slice of elements using implicit indexes with 'iloc':
 b    4
c    8
d    9
dtype: int64

In [11]:
# Access single element of a Series object by using the 'iat' 
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
print(ser1.iat[2])

8

In [12]:
### The ‘array’ attribute returns the array equivalent of the Series object. 
# Return the Python Array equivalent of the Series
arr1 = ser1.array
print(arr1)

<NumpyExtensionArray>
[3, 4, 8, 9, 5]
Length: 5, dtype: int64

In [13]:
## 'Axes' attritute Returns the Rw Axes Label, i.e. for a Series object, returns the index labels.
# Return the Row Axes labels
axes1 = ser1.axes
print(axes1)

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object')]

In [14]:
## The dtypes attributes return the datatype of the underlying values in the SSeries. In case of heterogeneity of data types in the Series, dtypes return an Object type. 
# Return the datatype of the underlying data with dtypes attribute
ser1 = pd.Series([3, 4, 8, 9, 5])     # All elements are of type int
ser2 = pd.Series(['a', 'b', 'c', 'd', 'e'])   # All elements are of type char
ser3 = pd.Series([12.3, 34.56, 45.999])    # All elements are of type float
ser4 = pd.Series([1, 's', 12.3, True])
print("Dtype of ser1 - ", ser1.dtypes)
print("Dtype of ser2 - ", ser2.dtypes)
print("Dtype of ser3 - ", ser3.dtypes)
print("Dtype of ser4 - ", ser4.dtypes)

Dtype of ser1 -  int64
Dtype of ser2 -  object
Dtype of ser3 -  float64
Dtype of ser4 -  object

In [15]:
## The hasnans attribute return whether or not there is any NaN value in the Series. NaN in Python data structures denote a missing value. 
# Return True if the Series has any NaN values, otherwise False
ser1 = pd.Series([3, 4, 8, 9, 5])     
print("Check whether ser1 has NaN values: ", ser1.hasnans)
ser1[2] = np.nan     # Asssign a NaN value to an element in ser1
print("Print ser1 \n", ser1)
print("Check whether ser1 has NaN values: ", ser1.hasnans)

Check whether ser1 has NaN values:  False
Print ser1
 0    3.0
1    4.0
2    NaN
3    9.0
4    5.0
dtype: float64
Check whether ser1 has NaN values:  True

In [16]:
## Returns the index values of the Series object.
# Print the Index labels of the Series object
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
print(ser1.index)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [17]:
## Returns the size of the Object in terms of total number of elements. 
# Print the size of the Series object
ser1 = pd.Series([1, 2, 2, 4, 4, 6])   
ser1.size

6

In [18]:
## Returns the values of the elements.
# Print the values of the Series object
ser1 = pd.Series([1, 2, 2, 4, 4, 6])   
ser1.values

array([1, 2, 2, 4, 4, 6])

In [19]:
## The ‘add’ method adds corresponding elements from two Series objects. 

# Check out the 'add' method to add corresponding elements from two Series objects
ser1 = pd.Series([1, 2, 2, 4, 4, 6])   
ser2 = pd.Series([10, 20, 20, 40, 40, 60])   
print(ser1.add(ser2))

0    11
1    22
2    22
3    44
4    44
5    66
dtype: int64

In [20]:
## The ‘astype’ method is used to cast the elements of a Pandas Series to another Data Type. In the following example, we are converting int elements to a string type. 

# Use of the 'astype' method to cast the elements to another data type 
ser1 = pd.Series([1, 2, 2, 4, 4, 6])   
print(list(ser1.astype(str)))

['1', '2', '2', '4', '4', '6']

In [21]:
## Extracts values of an element at a specified date/time in a Date/Time Index Series.

# Filter/Extract specific elements with date/time index Series
dt_tm = pd.date_range('2020-04-01', periods=5, freq='6H')
ser1 = pd.Series(['Sleep', 'Breakfast', 'Lunch', 'Snacks', 'Dinner'], index=dt_tm)
print("Series: \n", ser1)
print("\n", ser1.at_time('18:00'))

Series:
 2020-04-01 00:00:00        Sleep
2020-04-01 06:00:00    Breakfast
2020-04-01 12:00:00        Lunch
2020-04-01 18:00:00       Snacks
2020-04-02 00:00:00       Dinner
Freq: 6h, dtype: object

 2020-04-01 18:00:00    Snacks
Freq: 6h, dtype: object

C:\Users\91890\AppData\Local\Temp\ipykernel_21944\3284432129.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dt_tm = pd.date_range('2020-04-01', periods=5, freq='6H')

In [22]:
## The ‘between’ method returns a Boolean vector corresponding to all the elements in the passed Series as to whether or not each of the elements are between two other passed values. 

# Use the 'between' method to create a Boolean vector corresponding to all the elements in the passed Series 
# as to whether or not each of the elements are between two other passed values. 
ser1 = pd.Series([1, 2, 3, 4, 5, 6])
print(ser1.between(2,4))

0    False
1     True
2     True
3     True
4    False
5    False
dtype: bool

In [23]:
# Copies one Series to a new one.
# Deep copy: Creates a new object with values and indexes of the original Series. Change in any element in the 
# original Series will not reflect in the Deep copy.
# Shallow Copy: Creates a new object with references of values and indexes of the original Series. 
# Change in any element in the original Series will reflect in the Shallow copy.

# Series Deep Copy & Shallow Copy
ser1 = pd.Series([3, 4, 5])
ser2 = ser1.copy(deep=True)
ser1[2] = 8
print("Ser1: \n", ser1)
print("Ser2 - Deep Copy: \n", ser2)
ser3 = ser1.copy(deep=False)
ser1[2] = 8
print("Ser3 - Shallow Copy: \n", ser3)

Ser1:
 0    3
1    4
2    8
dtype: int64
Ser2 - Deep Copy:
 0    3
1    4
2    5
dtype: int64
Ser3 - Shallow Copy:
 0    3
1    4
2    8
dtype: int64

In [24]:
## Returns the number of elements in the Series.

# Count of Elements
ser1 = pd.Series([3, 4, 5])
print(ser1.count())

3

In [25]:
## Prints the Descriptive statistics of the Series elements.

# Print Discriptive Statistics of the Series elements
ser1 = pd.Series([12, 21, 14, 10, 15, 19])   
ser1.describe()

count     6.000000
mean     15.166667
std       4.167333
min      10.000000
25%      12.500000
50%      14.500000
75%      18.000000
max      21.000000
dtype: float64

In [26]:
## Divides corresponding elements from two Series Objects:

# 'div' method divides corresponding elements from two Series objects
ser1 = pd.Series([5, 4, 52, 64, 47, 45])   
ser2 = pd.Series([10, 20, 20, 40, 40, 60])   
print(round(ser1.div(ser2),2))

0    0.50
1    0.20
2    2.60
3    1.60
4    1.18
5    0.75
dtype: float64

In [27]:
## The ‘drop’ method removes the specified elements from a Series object. You can mention multiple labels/indexes as a List object in the parameter. It returns the updated Series after the drop operation. 

# Drop elements with specified label(s)
ser1 = pd.Series([3, 4, 8, 9, 5], index=['a', 'b', 'c', 'd', 'e'])   
ser2 = ser1.drop(labels=['c', 'e'])
print(ser2)

a    3
b    4
d    9
dtype: int64

In [28]:
## The ‘dropna’ method drops the ‘NaN’ (Null or missing) values from the Series.

# Drops the NaN elements in a Series
ser1 = pd.Series([3, 4, 8, 9, 5])     
ser1[2] = np.nan     # Asssign a NaN value to an element in ser1
print("Print ser1 \n", ser1)
print("Check the Series after dropping NaNs: \n", ser1.dropna())

Print ser1
 0    3.0
1    4.0
2    NaN
3    9.0
4    5.0
dtype: float64
Check the Series after dropping NaNs:
 0    3.0
1    4.0
3    9.0
4    5.0
dtype: float64

In [29]:
## Checks if two Series objects passed to it are equal.

# Validates if two Series objects are equal 
ser1 = pd.Series([3, 4, 8, 9, 5]) 
ser2 = pd.Series([3, 4, 8, 9, 5]) 
print(ser1.equals(ser2))

True

In [30]:
## Fills the NaN values in the Series object with a specified value.

# Fills the NaN elements in a Series with a Specified value
ser1 = pd.Series([3, 4, 8, 9, 5])     
ser1[2] = np.nan     # Asssign a NaN value to an element in ser1
print("Print ser1 \n", ser1)
print("Check the Series after filling NaNs: \n", ser1.fillna(12))

Print ser1
 0    3.0
1    4.0
2    NaN
3    9.0
4    5.0
dtype: float64
Check the Series after filling NaNs:
 0     3.0
1     4.0
2    12.0
3     9.0
4     5.0
dtype: float64

In [31]:
## The 'floordiv' method divides corresponding elements from two Series objects and returns the interger of the quotient. 

# 'floordiv' method divides corresponding elements from two Series objects and returns the interger of the quotient
ser1 = pd.Series([5, 4, 52, 64, 47, 45])   
ser2 = pd.Series([10, 20, 20, 40, 40, 60])   
print(ser1.floordiv(ser2))

0    0
1    0
2    2
3    1
4    1
5    0
dtype: int64

In [32]:
## The ‘groupby’ method groups elements of the same label together to enable performing a group operation such as mean, sum, etc. In the following example, we find the ‘mean’ of all the elements with HR and SALES labels respectively. Note, in this example, we also establish that Series elements can have same labels. 

# Grouping of series elements
ser1 = pd.Series([23, 34, 56, 76, 53, 54, 55, 87], index=['HR', 'HR', 'SALES', 'HR', 'SALES', 'HR', 'HR', 'SALES'])
ser1.groupby(level=0).sum()

HR       242
SALES    196
dtype: int64

In [33]:
## Print the first 5 elements from a Series. Usually used on Series with large numbers for ease of visual inspection. 

# Print the first 5 elements 
ser1 = pd.Series([5, 4, 52, 64, 47, 45, 20, 55, 54, 42, 88]) 
ser1.head(4)

0     5
1     4
2    52
3    64
dtype: int64

In [34]:
## The ‘idxmax’ method returns the label or index of the maximum value in a Series. 

# Return the label of the maximum value
ser1 = pd.Series([23, 34, 56, 76, 53, 54, 55, 87], index=['HR', 'FIN', 'SALES', 'MKTG', 'MANU', 'ADVT', 'OPS', 'QLTY'])
ser1.idxmax()

'QLTY'

In [35]:
## The ‘idxmin’ method returns the label or index of the minimum value in a Series. 

# Return the label of the minimum value
ser1 = pd.Series([23, 34, 56, 76, 53, 54, 55, 87], index=['HR', 'FIN', 'SALES', 'MKTG', 'MANU', 'ADVT', 'OPS', 'QLTY'])
ser1.idxmin()

'HR'

In [36]:
## Returns a Series/vector of whether a specified value equals to each of the corresponding Series object elements.
## In the next example, we check if 87 is part of ser1 and it checks agains each element and returns a Boolean vector. 

# Check for membership (if it is part of) of a specified value in a Series object
ser1 = pd.Series([23, 34, 56, 76, 53, 54, 55, 87])
ser1.isin([87])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [37]:
## Checks each element in a Series on whether it is a NaN value and returns a Series/vector of Boolean results. 

# Check for existance of NaN value against each of the elements
ser1 = pd.Series([23, 34, 56, None, 53, 54, 55, 87])
ser1.isna()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [38]:
## Return the ‘max’, ‘mean’, ‘min’ and ‘median’ of the values from the Series object.

# Return 'max', 'min', 'mean', 'median' values of a Series
ser1 = pd.Series([23, 34, 56, 43, 53, 54, 55, 87])
print("The Maximum Value element: ", ser1.max())
print("The Minimum Value element: ", ser1.min())
print("The Mean of all elements: ", ser1.mean())
print("The Median value among all elements: ", ser1.median())

The Maximum Value element:  87
The Minimum Value element:  23
The Mean of all elements:  50.625
The Median value among all elements:  53.5

In [39]:
## The ‘multiply method multiplies corresponding elements from two Series objects. 

#  Use of the 'multiply'' method to multiply corresponding elements from two Series objects
ser1 = pd.Series([1, 2, 2, 4, 4, 6])   
ser2 = pd.Series([10, 20, 20, 40, 40, 60])   
print(ser1.multiply(ser2))

0     10
1     40
2     40
3    160
4    160
5    360
dtype: int64

In [40]:
## The ‘replace’ method replaces a specified value in the Series with another. The ‘replace’ method returns a 
## modified Series and the original series remains unchanged. The ‘inplace’ parameter has to be set to True 
## if the original Series object is to be updated. 

# Replace a spcified value in the Series with another
ser1 = pd.Series([23, 34, 56, 66, 53, 54, 55, 87])
ser2 = ser1.replace({34:55})
print("Printing ser2: \n", ser2)
ser1.replace({34:55}, inplace=True)
print("Printing ser1 after replacing inplace:\n", ser1)

Printing ser2:
 0    23
1    55
2    56
3    66
4    53
5    54
6    55
7    87
dtype: int64
Printing ser1 after replacing inplace:
 0    23
1    55
2    56
3    66
4    53
5    54
6    55
7    87
dtype: int64

In [41]:
## The ‘round’ method rounds off the series elements to a specified position. In the following example, it rounds off to 2nd decimal place. 

# Rounding off Series elements 
ser1 = pd.Series([23.8567876, 34.76465354, 56.53439, 43.09775454, 53.63654, 5.8755424, 5.858765, 8.656547])
print(ser1.round(2))

0    23.86
1    34.76
2    56.53
3    43.10
4    53.64
5     5.88
6     5.86
7     8.66
dtype: float64

In [42]:
## The ‘std’ method returns the Standard Deviation of all the elements of a Series Object.

# Find the standard deviation using the std method
ser1 = pd.Series([23, 34, 56, 66, 53, 54, 55, 87])
stdv = ser1.std()
print(round(stdv, 2))

19.27

In [43]:
## ‘str’ enables String functions to be applied on Series objects.

# Enables operation of string functions on string type elements 
ser1 = pd.Series(['HR', 'FIN', 'SALES', 'MKTG', 'MANU', 'ADVT', 'OPS', 'QLTY'])
ser1_str = ser1.str.replace('M', 'Y')
print(ser1_str)

0       HR
1      FIN
2    SALES
3     YKTG
4     YANU
5     ADVT
6      OPS
7     QLTY
dtype: object

In [44]:
## The ‘sub’ function subtracts numeric elements of one Series element from corresponding elements of the original one.

# Subtraction of one Series elements from another
ser1 = pd.Series([5, 4, 52, 64, 47, 45, 20, 55, 54, 42, 88]) 
ser2 = pd.Series([1, 3, 35, 33, 89, 57, 46, 22, 34, 32, 44]) 
print(ser1.sub(ser2))

0      4
1      1
2     17
3     31
4    -42
5    -12
6    -26
7     33
8     20
9     10
10    44
dtype: int64

In [45]:
## The ‘to_dict’ method converts a Series object to a Python Dictionary. The Indexes get converted into ‘key’s and the Series element values are copied as ‘values’ into the output dictionary. 

# Convert a Series object to a Dictionary 
ser1 = pd.Series([23, 34, 56, 76, 53, 54, 55, 87], index=['HR', 'FIN', 'SALES', 'MKTG', 'MANU', 'ADVT', 'OPS', 'QLTY'])
ser1dict = ser1.to_dict()
print(ser1dict)

{'HR': 23, 'FIN': 34, 'SALES': 56, 'MKTG': 76, 'MANU': 53, 'ADVT': 54, 'OPS': 55, 'QLTY': 87}

In [50]:
## The ‘truncate’ method truncates a Series object based on a ‘before’ or ‘after’ index values. ‘before=3’ 
## parameter indicates truncation of all elements before index number 3. ‘after=3’ indicates truncation of all 
## elements after the index value 3. 

# Truncate a Series Object
ser1 = pd.Series([23, 34, 56, 76, 53, 54, 55, 87])
sert1 = ser1.truncate(before=3)
print(sert1)
sert2 = ser1.truncate(after=3)
print(sert2)

3    76
4    53
5    54
6    55
7    87
dtype: int64
0    23
1    34
2    56
3    76
dtype: int64

In [51]:
## The ‘unique’ method returns unique elements from the Series object after removing all the duplicates.

# Find Unique elements in a Series
ser1 = pd.Series([23, 34, 23, 76, 53, 53, 55, 87])
ser1unq = ser1.unique()
print(ser1unq)

[23 34 76 53 55 87]

In [52]:
## The ‘var’ method finds the Variance of all numeric elements in a Series. 

# Find Variance of all elements in a Series
ser1 = pd.Series([23, 34, 23, 76, 53, 53, 55, 87])
variance = ser1.var()
print(round(variance, 2))

542.86

In [53]:
# Create a Multi-level Index Series Object
index = [('Tendulkar', 'Tests'), ('Tendulkar', 'ODIs'), ('Sangakkara', 'Tests'), 
         ('Sangakkara', 'ODIs'), ('Ponting', 'Tests'), ('Ponting', 'ODIs')]
runs = [16000, 18000, 12000, 14000, 13000, 13000]
index = pd.MultiIndex.from_tuples(index)
records = pd.Series(runs, index=index)
print(records)

Tendulkar   Tests    16000
            ODIs     18000
Sangakkara  Tests    12000
            ODIs     14000
Ponting     Tests    13000
            ODIs     13000
dtype: int64

In [54]:
print("Printing all of Sangakkara's Records: \n", records.loc['Sangakkara'])
print("Printing Tendulkar's ODI record: \n", records.loc['Tendulkar', 'ODIs'])
print("Printing Ponting's Test record: \n", records.iloc[4])
print("Printing Ponting's Test record - direct Index Access: \n", records[4])

Printing all of Sangakkara's Records:
 Tests    12000
ODIs     14000
dtype: int64
Printing Tendulkar's ODI record:
 18000
Printing Ponting's Test record:
 13000
Printing Ponting's Test record - direct Index Access:
 13000

C:\Users\91890\AppData\Local\Temp\ipykernel_21944\1037254802.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Printing Ponting's Test record - direct Index Access: \n", records[4])

In [55]:
import numpy as np
import pandas as pd

In [58]:
# Create a DataFrame from a Dictionary

dict = {
    'Car_Brand': ['Ford', 'Toyota', 'Renault', 'Tata', 'Mahindra'], 
    'Avg_Yearly_Sale': [20000, 22000, 31000, 27000, 19000],
    'Best_Selling_Model': ['Ecosport', 'Fortuner', 'Duster', 'Nexon', 'Scorpio']}

car_df = pd.DataFrame(dict)
car_df

  Car_Brand  Avg_Yearly_Sale Best_Selling_Model
0      Ford            20000           Ecosport
1    Toyota            22000           Fortuner
2   Renault            31000             Duster
3      Tata            27000              Nexon
4  Mahindra            19000            Scorpio

In [59]:
# Create a DataFrame from a Numpy Array of Arrays

nparr = np.array(
    [['Ford', 'Toyota', 'Renault', 'Tata', 'Mahindra'],
     [20000, 22000, 31000, 27000, 19000],
     ['Ecosport', 'Fortuner', 'Duster', 'Nexon', 'Scorpio']])

dictarr = {
    'Car_Brand': nparr[0],
    'Avg_Yearly_Sale': nparr[1],
    'Best_Selling_Model': nparr[2]}

dfarr = pd.DataFrame(dictarr)
dfarr

  Car_Brand Avg_Yearly_Sale Best_Selling_Model
0      Ford           20000           Ecosport
1    Toyota           22000           Fortuner
2   Renault           31000             Duster
3      Tata           27000              Nexon
4  Mahindra           19000            Scorpio

In [60]:
# Create a DataFrame from a List of Lists

list1 = [
    ['Ford', 20000, 'Ecosport'],
    ['Toyota', 22000, 'Fortuner'],
    ['Renault', 31000, 'Duster'],
    ['Tata', 27000, 'Nexon'],
    ['Mahindra', 19000, 'Scorpio']]

dflist = pd.DataFrame(list1, columns = ['Car_Brand', 'Avg_Yearly_Sale', 'Best_Selling_Model'])
dflist

  Car_Brand  Avg_Yearly_Sale Best_Selling_Model
0      Ford            20000           Ecosport
1    Toyota            22000           Fortuner
2   Renault            31000             Duster
3      Tata            27000              Nexon
4  Mahindra            19000            Scorpio

In [61]:
# Create a DataFrame from a list of Series Objects (use of Dictionary as intermediate)

series1 = pd.Series(['Ford', 'Toyota', 'Renault', 'Tata', 'Mahindra'])
series2 = pd.Series([20000, 22000, 31000, 27000, 19000])
series3 = pd.Series(['Ecosport', 'Fortuner', 'Duster', 'Nexon', 'Scorpio'])
dictionary_of_nparray = {'Name': series1, 'Sale': series2, 'Best_Model':series3}

dfser = pd.DataFrame(dictionary_of_nparray)
dfser

       Name   Sale Best_Model
0      Ford  20000   Ecosport
1    Toyota  22000   Fortuner
2   Renault  31000     Duster
3      Tata  27000      Nexon
4  Mahindra  19000    Scorpio

In [62]:
# Creating a DataFrame with dates as Row Indexes

# Generate a range of dates between 1st Jan 21 to 31st Jan 21.

rng = pd.date_range("1/1/2021", periods=31, freq="D")

# Generate two sets of 31 random numbers

s1 = np.random.rand(31)
s2 = np.random.rand(31)
s3 = np.random.rand(31)

# Create a DataFrame with the dates as Row Indexes

df1 = pd.DataFrame({'feature1': s1, 'feature2': s2, 'feature3':s3})
df1.set_index(rng)
#df1.shape

            feature1  feature2  feature3
2021-01-01  0.986219  0.227286  0.218883
2021-01-02  0.457210  0.095983  0.268700
2021-01-03  0.006963  0.326865  0.015987
2021-01-04  0.314545  0.729664  0.245716
2021-01-05  0.917503  0.959164  0.784010
2021-01-06  0.321903  0.166874  0.464435
2021-01-07  0.624287  0.812734  0.719186
2021-01-08  0.245903  0.302021  0.386096
2021-01-09  0.878070  0.950348  0.336174
2021-01-10  0.405736  0.246111  0.546321
2021-01-11  0.411317  0.958443  0.096345
2021-01-12  0.091608  0.264603  0.759978
2021-01-13  0.744386  0.177352  0.065534
2021-01-14  0.319870  0.708342  0.211036
2021-01-15  0.255644  0.323483  0.371640
2021-01-16  0.406717  0.675140  0.233609
2021-01-17  0.203609  0.351661  0.650996
2021-01-18  0.028413  0.549745  0.976806
2021-01-19  0.372989  0.222679  0.097840
2021-01-20  0.599556  0.333928  0.350116
2021-01-21  0.911664  0.270979  0.037433
2021-01-22  0.039493  0.145835  0.648824
2021-01-23  0.355121  0.915756  0.186856
2021-01-24  0.823260  0.199339  0.333559
2021-01-25  0.255025  0.689464  0.159906
2021-01-26  0.943504  0.608418  0.828589
2021-01-27  0.648642  0.718258  0.057935
2021-01-28  0.273134  0.542311  0.444237
2021-01-29  0.176557  0.594999  0.230240
2021-01-30  0.153930  0.101175  0.034762
2021-01-31  0.399973  0.525123  0.306453

In [63]:
# Obtaining Statistical details about the Numeric data in DataFrame

df1.describe()

        feature1   feature2   feature3
count  31.000000  31.000000  31.000000
mean    0.437831   0.474003   0.357039
std     0.293085   0.279062   0.264896
min     0.006963   0.095983   0.015987
25%     0.250464   0.236699   0.173381
50%     0.372989   0.351661   0.306453
75%     0.636464   0.698903   0.505378
max     0.986219   0.959164   0.976806

In [64]:
# Transpose the DataFrame

dfT = df1.transpose()
dfT

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
feature1,0.986219,0.457210,0.006963,0.314545,0.917503,0.321903,0.624287,0.245903,0.878070,0.405736,...,0.039493,0.355121,0.823260,0.255025,0.943504,0.648642,0.273134,0.176557,0.153930,0.399973
feature2,0.227286,0.095983,0.326865,0.729664,0.959164,0.166874,0.812734,0.302021,0.950348,0.246111,...,0.145835,0.915756,0.199339,0.689464,0.608418,0.718258,0.542311,0.594999,0.101175,0.525123
feature3,0.218883,0.268700,0.015987,0.245716,0.784010,0.464435,0.719186,0.386096,0.336174,0.546321,...,0.648824,0.186856,0.333559,0.159906,0.828589,0.057935,0.444237,0.230240,0.034762,0.306453

In [65]:
dflist

  Car_Brand  Avg_Yearly_Sale Best_Selling_Model
0      Ford            20000           Ecosport
1    Toyota            22000           Fortuner
2   Renault            31000             Duster
3      Tata            27000              Nexon
4  Mahindra            19000            Scorpio

In [66]:
# Sort your DataFrame on a column

dfsort = dflist.sort_values(by='Avg_Yearly_Sale', ascending=True)

In [67]:
dfsort

  Car_Brand  Avg_Yearly_Sale Best_Selling_Model
4  Mahindra            19000            Scorpio
0      Ford            20000           Ecosport
1    Toyota            22000           Fortuner
3      Tata            27000              Nexon
2   Renault            31000             Duster

In [72]:
def testfunc(x, y):
    """
    This is a test function for learning purposes.
    And we will also learn the use of Docstrings. 
    """
    
    print(f"First Argument is {x}")
    print(f"Second Argument is {y}")
    return x*y, x+y, x/y

In [73]:
print(testfunc(4,8))

First Argument is 4
Second Argument is 8
(32, 12, 0.5)

In [74]:
ret1, ret2, ret3 = testfunc(8,9)
print(ret1)
print(ret2)
print(round(ret3, 2))

First Argument is 8
Second Argument is 9
72
17
0.89

In [75]:
def testfunc(x, y):
    testvar_l = 7     # Available only within the Function
    print("testvar_g:", testvar_g)
    print(f"First Argument is {x}")
    print(f"Second Argument is {y}")
    return x*y+testvar_g

In [76]:
testvar_g = 5
print(testfunc(4,5))

testvar_g: 5
First Argument is 4
Second Argument is 5
25

In [77]:
# In the folowing code, we will perform an operation to find the cube of a given number.
# To do that, we will use three different methods:
# - Use a traditional Python function created using 'def'
# - Create a named Lambda function
# - Use an Inline Lambda function

from time import time_ns

def cubed(x):
        return x**3

lambda_cubed = lambda x:x**3

start = time_ns()   # Returns time in nanoseconds since epoch (Jan 1, 1970) 

print(f"Cube of 9 is {cubed(9)}")
print(f"Time taken by traditional method : {(time_ns()-start)//1000} ms\n")

start = time_ns()

print(f"Cube of 9 is {lambda_cubed(9)}")
print(f"Time taken by named lambda function: {(time_ns()-start)//1000} ms\n")

start = time_ns()
print(f"Cube of 9 is {(lambda x:x**3)(9)}")
print(f"Time taken by inline lambda function: {(time_ns()-start)//1000} ms")

Cube of 9 is 729
Time taken by traditional method : 998 ms

Cube of 9 is 729
Time taken by named lambda function: 0 ms

Cube of 9 is 729
Time taken by inline lambda function: 1001 ms

In [78]:
numbers = [4, 5, 7, 9, 12, 23]
mapped_numbers = list(map(lambda x: x^3 + x^2 + 5*x - 8, numbers))
print(mapped_numbers)

[13, 30, 16, 34, 53, 96]

In [80]:
# E.g. We are to return all number greater than 5 from a list of numbers

numbers = [4, 3, 6, 7, 3, 9, 11]

def filt_gt5(num):
    return num < 5

In [81]:
filt = filter(filt_gt5, numbers)
list(filt)

[4, 3, 3]

In [82]:
# Can also be inline filter using a Lambda function

filt = filter(lambda x: x > 5, numbers)
list(filt)

[6, 7, 9, 11]